### ISSUE TITLE
Is this project still going on?

### ISSUE THREAD

**Issue by oren-z0** [chmac/nostr-map#2]
I've thought about the same project idea, and then stumbled: https://chmac.github.io/nostr-map/

Also opened the following issues to allow better indexing of geo-hashes:
https://github.com/Cameri/nostream/issues/265 

I think it would be really cool to see unfiltered opinions that the public/anonymous people you follow write on restaurants, attractions, etc. And since it is decentralized, if business owners see negative opinions on their location written by anonymous people, they wouldn't so-easily be able to sue the website/platform for spreading defamation.

Also, business owners could publish their lightning address to receive tips - maybe somebody should verify that the address was published by the business owner, not by some random impostor.

I had troubles zooming in and writing notes on exact locations. I could only write notes on really large geohash rectangles, but the general implementation looks great.

P.S. Did you consider collaborating with https://btcmap.org ?

**Comment by chmac** [comment]
@oren-z0 Yeah, the idea is you can only write notes on rectangles. We're using Open Location Code instead of geohash, it seems to have some advantages. But our next project is actually exactly what you described, to see if we can get prefix search into arbitrary tags!

> Is this project still going on?

Well, depends on your definition of "going on"! We wrote it as a test project to start playing with maps and nostr. It seems to work for the intended purpose, but we are unlikely to develop it much further, we're probably not adding new features, etc. Although I guess I'd fix bugs if they came up.

**Comment by oren-z0** [comment]
@chmac Are you working in public on the next project? Did you think about raising money for it, maybe after building a small demo?

**Comment by chmac** [comment]
The next project is the prefix search. So yeah, we'll be trying to get a NIP added, try to submit PRs to some relays and see if they'll add support. Exactly as you described, being able to prefix search geo tags. @fiatjaf suggested using the format `^foo`, makes a lot of sense I think.

**Comment by oren-z0** [comment]
Like `^` from RegExps? Nice.
Let me know if you post a NIP and I'll upvote it.
It could also be awesome to write a smartphone app like Damus (or maybe suggest Damus to implement it). Anyways, it must be a "mobile-first" design, because usually people check for information about places when they are at the location or on the go. I have experience with Typescript, Node.JS and React - if you want me to contribute, please let me know.

**Comment by pats2sats** [comment]
Any update on this? Seems like a very complicated issue.

**Comment by chmac** [comment]
@PatrickGeyer nothing yet.
